apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: keycloak-auth-middleware
  namespace: oauth2-proxy
spec:
  forwardAuth:
    address: https://auth2.scmeyer.dev/oauth2/auth
    trustForwardHeader: true
    authRequestHeaders:
      - X-Forwarded-Uri
      - X-Forwarded-Method
      - X-Forwarded-Host
      - Authorization
      - Cookie
    authResponseHeaders:
      - X-Auth-Request-User
      - X-Auth-Request-Email
      - X-Auth-Request-Preferred-Username
      - Authorization
      - Set-Cookie
