apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: keycloak-auth-middleware
spec:
  forwardAuth:
    address: http://oauth2-proxy.oauth2-proxy.svc.cluster.local/
    trustForwardHeader: true
    authResponseHeaders:
      - X-Auth-Request-User
      - Set-Cookie