apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: akri
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'git@github.com:Synthint/testing.git'
    path: akri
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: akri
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true