apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cloudflared-tunnel
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'git@github.com:Synthint/testing.git'
    path: cloudflared
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: cloudflared
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true