apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: 1password
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://1password.github.io/connect-helm-charts'
    chart: connect
    targetRevision: 1.16.0
    helm:
      parameters:
        - name: operator.autoRestart
          value: 'true'
        - name: operator.pollingInterval
          value: '60'
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: one-pass
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true