apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openproject
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'git@github.com:Synthint/testing.git'
    path: openproject
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: openproject
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true