akri:
  controller:
    enabled: true
    onlyOnControlPlane: false
    allowOnControlPlane: true
    resources:
      memoryRequest: 11Mi
      cpuRequest: 10m
      memoryLimit: 100Mi
      cpuLimit: 26m
  agent:
    enabled: true
    full: true
    resources:
      memoryRequest: 11Mi
      cpuRequest: 10m
      memoryLimit: 79Mi
      cpuLimit: 26m
  udev:
    configuration:
      enabled: true
      name: akri-udev
      discoveryDetails:
        groupRecursive: false
        udevRules:
        - 'SUBSYSTEM=="video4linux", KERNEL=="video0"'
        - 'SUBSYSTEM=="video4linux", KERNEL=="video1"'
      brokerPod:
        image:
          repository: ghcr.io/project-akri/akri/udev-video-broker
          tag: latest
          pullPolicy: Always
        securityContext:
          privileged: true
        volumeMounts:
          - name: dev
            mountPath: /dev
        volumes:
          - name: dev
            hostPath:
              path: /dev
              type: Directory
      discovery:
        enabled: true
        image:
          repository: ghcr.io/project-akri/akri/udev-discovery
          tag:
          pullPolicy: "Always"